### ISSUE TITLE
Does bstga2png actually work?

### ISSUE THREAD

**Issue by composedevelopment** [puggsoy/MiscTools#2]
There seems to be several issues with your program, and I'm curious if it ever actually functioned or not.

For example, the line `if (file.substr( -4, 4) == ".bstga")` would never actually equate to `true`; it only gets "**stga**", so you need it to be `-6, 6` instead.

But even when that's fixed, or the files are loaded directly, I can't get the `loadFile()` function to ever work. This seems to be for two reasons relating to the "length" variable:

- There's an issue at `var pxlBytes:Bytes = Bytes.alloc(length);`, with the error **Invalid_argument("Bytes.create")** due to the `length` variable being a negative value, like **-1458548725** for **television01_02.bstga**.

- If it's not negative, it's way too big and causes an **Uncaught exception Eof** error. And the same exact length value is found for nearly every file, **184560671**, which alone tells you that it's wrong – each one should be unique.

I'm almost certainly using the program correctly, and I wouldn't imagine that Haxe's file reading functions would've completely changed how they work in the past 8 years, so I would greatly appreciate your input and insight about this, thank you!

**Comment by puggsoy** [comment]
You're right about the line that grabs the extension, that's incorrect. It's honestly quite possible that I never finished working on this. All of these programs are quick, one-off projects for specific requests.

Unfortunately I have no insight into your other issues, the only thing I could suggest is that the files you're using aren't the same format as what the program was designed for. Either that, or it never worked in the first place (unfortunately the VG Resource thread related to the original request seems to have been removed and I can't remember).

**Comment by composedevelopment** [comment]
Thank you for responding. For reference, I used DSLazy to NDS Unpack the MySims DS ROM, and am using the .bstga texture files within its folders. 
Feel free to close this issue if you're not planning on revisiting the project, but I think it would be very cool if you looked into this again. I'm curious what the fix would be, as well as the process for reverse-engineering/identifying the file information and making a tool like this. Anything you can share will help me with handling this kind of stuff myself 😄

**Comment by puggsoy** [comment]
Unfortunately I don't see myself having the time to take care of this among all the other things I have on my plate, so I will close it. Maybe in the future myself or someone else will take a look at it again though.
